import { Question, FamilyProfile } from './types';

export const QUESTIONS: Question[] = [
  {
    id: 1,
    category: 'Tiempo libre',
    text: '¿Qué harías un sábado por la mañana sin planes?',
    options: [
      {
        id: 'a',
        emoji: '🎮',
        text: 'Explorar apps, aprender algo de tecnología o programar',
        weights: { tecnologia: 3, precision: 1 },
      },
      {
        id: 'b',
        emoji: '🤝',
        text: 'Quedar con amigos, organizar algo o ayudar a alguien',
        weights: { personas: 2, comunicacion: 2 },
      },
      {
        id: 'c',
        emoji: '🎨',
        text: 'Crear algo: dibujar, diseñar, tocar música o hacer manualidades',
        weights: { creatividad: 3, arte: 2 },
      },
      {
        id: 'd',
        emoji: '🏃',
        text: 'Hacer deporte, salir al campo o arreglar algo con mis manos',
        weights: { fisico: 3, naturaleza: 1 },
      },
    ],
  },
  {
    id: 2,
    category: 'Asignatura favorita',
    text: '¿Qué tipo de asignatura se te da mejor o más te gusta?',
    options: [
      {
        id: 'a',
        emoji: '💻',
        text: 'Tecnología, informática o matemáticas aplicadas',
        weights: { tecnologia: 3, precision: 2 },
      },
      {
        id: 'b',
        emoji: '🌿',
        text: 'Biología, química o ciencias naturales',
        weights: { ciencia: 3, naturaleza: 1 },
      },
      {
        id: 'c',
        emoji: '🎭',
        text: 'Lengua, plástica o educación artística',
        weights: { comunicacion: 2, arte: 2, creatividad: 1 },
      },
      {
        id: 'd',
        emoji: '📊',
        text: 'Economía, empresa o gestión',
        weights: { negocio: 3, precision: 2 },
      },
    ],
  },
  {
    id: 3,
    category: 'Entorno de trabajo',
    text: '¿En qué tipo de lugar te imaginas trabajando en el futuro?',
    options: [
      {
        id: 'a',
        emoji: '💻',
        text: 'Delante de un ordenador, resolviendo problemas digitales',
        weights: { tecnologia: 3, precision: 1 },
      },
      {
        id: 'b',
        emoji: '🏥',
        text: 'Con personas que necesitan ayuda, cuidado o atención',
        weights: { personas: 3, ciencia: 1 },
      },
      {
        id: 'c',
        emoji: '🏗️',
        text: 'Construyendo, instalando o reparando cosas físicas',
        weights: { construccion: 3, fisico: 2 },
      },
      {
        id: 'd',
        emoji: '🌳',
        text: 'En la naturaleza, con animales o en entornos sostenibles',
        weights: { naturaleza: 3, fisico: 1 },
      },
    ],
  },
  {
    id: 4,
    category: 'Trabajo en equipo',
    text: 'En un trabajo grupal, ¿qué papel sueles tomar?',
    options: [
      {
        id: 'a',
        emoji: '🧩',
        text: 'El que organiza, coordina y gestiona los plazos',
        weights: { negocio: 3, precision: 2 },
      },
      {
        id: 'b',
        emoji: '🎤',
        text: 'El que explica, presenta y convence al resto',
        weights: { comunicacion: 3, creatividad: 1 },
      },
      {
        id: 'c',
        emoji: '🔧',
        text: 'El que investiga y busca la solución técnica',
        weights: { tecnologia: 2, ciencia: 2, precision: 1 },
      },
      {
        id: 'd',
        emoji: '🤗',
        text: 'El que cuida el ambiente y se asegura de que todos estén bien',
        weights: { personas: 3, servicio: 1 },
      },
    ],
  },
  {
    id: 5,
    category: 'Tipo de desafío',
    text: '¿Qué tipo de problema disfrutas más resolviendo?',
    options: [
      {
        id: 'a',
        emoji: '🔍',
        text: 'Descubrir por qué algo no funciona y arreglarlo paso a paso',
        weights: { precision: 3, tecnologia: 2, ciencia: 1 },
      },
      {
        id: 'b',
        emoji: '💬',
        text: 'Ayudar a alguien a sentirse mejor o resolver su situación personal',
        weights: { personas: 3, comunicacion: 2 },
      },
      {
        id: 'c',
        emoji: '✨',
        text: 'Crear algo original y bonito que no existía antes',
        weights: { creatividad: 3, arte: 2 },
      },
      {
        id: 'd',
        emoji: '📦',
        text: 'Organizar procesos y hacer las cosas más eficientes',
        weights: { negocio: 3, precision: 2 },
      },
    ],
  },
  {
    id: 6,
    category: 'Curiosidad',
    text: '¿Qué mundo te genera más curiosidad o admiración?',
    options: [
      {
        id: 'a',
        emoji: '🖥️',
        text: 'La tecnología, el software y la inteligencia artificial',
        weights: { tecnologia: 3, ciencia: 1 },
      },
      {
        id: 'b',
        emoji: '🩺',
        text: 'La salud, el cuerpo humano y los cuidados médicos',
        weights: { ciencia: 3, personas: 1 },
      },
      {
        id: 'c',
        emoji: '🏗️',
        text: 'La construcción, la arquitectura y las instalaciones',
        weights: { construccion: 3, fisico: 1 },
      },
      {
        id: 'd',
        emoji: '🍽️',
        text: 'La gastronomía, el turismo y los servicios a personas',
        weights: { servicio: 3, creatividad: 1 },
      },
    ],
  },
  {
    id: 7,
    category: 'Tu mejor rasgo',
    text: '¿Cuál de estas palabras te define mejor?',
    options: [
      {
        id: 'a',
        emoji: '🧪',
        text: 'Analítico/a: me gustan los datos, la lógica y los sistemas',
        weights: { precision: 3, tecnologia: 1, ciencia: 1 },
      },
      {
        id: 'b',
        emoji: '🌱',
        text: 'Empático/a: entiendo a las personas y sus necesidades profundas',
        weights: { personas: 3, comunicacion: 2 },
      },
      {
        id: 'c',
        emoji: '🚀',
        text: 'Creativo/a: imagino cosas nuevas y me gusta innovar',
        weights: { creatividad: 3, arte: 2 },
      },
      {
        id: 'd',
        emoji: '💪',
        text: 'Práctico/a: me gusta hacer cosas y ver resultados reales',
        weights: { fisico: 3, construccion: 1 },
      },
    ],
  },
  {
    id: 8,
    category: 'Empresa ideal',
    text: '¿En qué tipo de organización te gustaría trabajar?',
    options: [
      {
        id: 'a',
        emoji: '🏢',
        text: 'Una empresa de tecnología, software o telecomunicaciones',
        weights: { tecnologia: 3, negocio: 1 },
      },
      {
        id: 'b',
        emoji: '🏫',
        text: 'Un hospital, residencia, colegio o servicio social',
        weights: { personas: 3, ciencia: 1 },
      },
      {
        id: 'c',
        emoji: '🏭',
        text: 'Una fábrica, taller, obra o empresa industrial',
        weights: { fisico: 2, construccion: 2, precision: 1 },
      },
      {
        id: 'd',
        emoji: '🛒',
        text: 'Un comercio, agencia, restaurante o empresa de servicios',
        weights: { negocio: 2, servicio: 3, comunicacion: 1 },
      },
    ],
  },
  {
    id: 9,
    category: 'Cómo aprendes',
    text: 'Cuando tienes que aprender algo nuevo, ¿qué prefieres?',
    options: [
      {
        id: 'a',
        emoji: '📚',
        text: 'Leer, investigar y entender bien la teoría antes de empezar',
        weights: { ciencia: 2, precision: 2, tecnologia: 1 },
      },
      {
        id: 'b',
        emoji: '🧑‍🔬',
        text: 'Ponerme a probar directamente hasta que funcione',
        weights: { fisico: 2, tecnologia: 2, construccion: 1 },
      },
      {
        id: 'c',
        emoji: '🎥',
        text: 'Ver cómo otros lo hacen y darle mi toque propio',
        weights: { creatividad: 2, arte: 2, servicio: 1 },
      },
      {
        id: 'd',
        emoji: '🗣️',
        text: 'Que alguien me lo explique y poder preguntarle dudas',
        weights: { comunicacion: 2, personas: 2 },
      },
    ],
  },
  {
    id: 10,
    category: 'Impacto deseado',
    text: '¿Qué tipo de impacto quieres tener con tu trabajo?',
    options: [
      {
        id: 'a',
        emoji: '🌐',
        text: 'Crear tecnología que mejore cómo la gente trabaja o se conecta',
        weights: { tecnologia: 3, negocio: 1 },
      },
      {
        id: 'b',
        emoji: '❤️',
        text: 'Mejorar directamente la vida y el bienestar de personas',
        weights: { personas: 3, ciencia: 1 },
      },
      {
        id: 'c',
        emoji: '🏗️',
        text: 'Construir cosas duraderas: edificios, infraestructuras, instalaciones',
        weights: { construccion: 3, fisico: 1 },
      },
      {
        id: 'd',
        emoji: '✨',
        text: 'Entretener, embellecer o hacer que la gente disfrute más',
        weights: { arte: 3, creatividad: 2, servicio: 1 },
      },
    ],
  },
  {
    id: 11,
    category: 'Con qué trabajas',
    text: '¿Con qué tipo de "materia" disfrutas más trabajando?',
    options: [
      {
        id: 'a',
        emoji: '📐',
        text: 'Datos, código, circuitos o sistemas técnicos',
        weights: { tecnologia: 2, precision: 3 },
      },
      {
        id: 'b',
        emoji: '👥',
        text: 'Personas, equipos, clientes y relaciones humanas',
        weights: { comunicacion: 2, personas: 3 },
      },
      {
        id: 'c',
        emoji: '🌿',
        text: 'La naturaleza: tierra, animales, plantas o alimentos',
        weights: { naturaleza: 3, fisico: 1 },
      },
      {
        id: 'd',
        emoji: '🎨',
        text: 'Colores, formas, materiales o elementos visuales',
        weights: { arte: 3, creatividad: 2 },
      },
    ],
  },
  {
    id: 12,
    category: 'Futuro profesional',
    text: '¿Cuál de estas salidas profesionales te llama más la atención?',
    options: [
      {
        id: 'a',
        emoji: '🧑‍💻',
        text: 'Programador/a, técnico/a IT o especialista en redes',
        weights: { tecnologia: 3, precision: 1 },
      },
      {
        id: 'b',
        emoji: '🧑‍⚕️',
        text: 'Auxiliar sanitario/a, técnico/a en salud o en bienestar social',
        weights: { ciencia: 2, personas: 3 },
      },
      {
        id: 'c',
        emoji: '🧑‍🍳',
        text: 'Chef, técnico/a en hostelería, agente de viajes o estilista',
        weights: { servicio: 3, creatividad: 1 },
      },
      {
        id: 'd',
        emoji: '🏗️',
        text: 'Electricista, mecánico/a, instalador/a o técnico/a de obra',
        weights: { fisico: 2, construccion: 3 },
      },
    ],
  },
];

export const FAMILIES: FamilyProfile[] = [
  {
    codigo: 'IFC',
    nombre: 'Informática y Comunicaciones',
    emoji: '💻',
    colorFrom: '#1e3a5f',
    colorTo: '#2563eb',
    textColor: 'white',
    weights: { tecnologia: 10, precision: 7, creatividad: 5, negocio: 3, comunicacion: 3 },
    tagline: 'Construye el mundo digital del futuro',
    descripcion:
      'Diseña, desarrolla y mantiene los sistemas informáticos y redes que hacen funcionar empresas, instituciones y servicios digitales.',
    queAprenderas: [
      'Programación web y de aplicaciones',
      'Administración de sistemas y redes',
      'Ciberseguridad y protección de datos',
      'Bases de datos y servicios en la nube',
    ],
    salidasProfesionales: [
      'Desarrollador/a web o de aplicaciones',
      'Técnico/a de redes y sistemas',
      'Administrador/a de bases de datos',
      'Especialista en ciberseguridad',
      'Técnico/a de soporte informático',
    ],
    perfilTipico:
      'Personas curiosas con la tecnología, que disfrutan resolviendo problemas lógicos y aprenden fácilmente lenguajes de programación.',
    ciclosDestacados: [
      'Desarrollo de Aplicaciones Web (DAW) — Grado Superior',
      'Administración de Sistemas Informáticos en Red (ASIR) — Grado Superior',
      'Desarrollo de Aplicaciones Multiplataforma (DAM) — Grado Superior',
      'Sistemas Microinformáticos y Redes (SMR) — Grado Medio',
    ],
    ventajas: [
      'Alta demanda laboral — los técnicos IT son de los más buscados',
      'Posibilidad de trabajar en remoto desde cualquier lugar',
      'Sectores muy variados: sanidad, banca, industria, entretenimiento',
    ],
    nivelRecomendado: 'Grado Superior',
    queryParam: 'Informática y Comunicaciones',
  },
  {
    codigo: 'SAN',
    nombre: 'Sanidad',
    emoji: '🩺',
    colorFrom: '#064e3b',
    colorTo: '#10b981',
    textColor: 'white',
    weights: { ciencia: 10, personas: 9, precision: 8, servicio: 5 },
    tagline: 'Cuida y mejora la vida de las personas',
    descripcion:
      'Trabaja en hospitales, centros de salud y servicios sociosanitarios cuidando y atendiendo a pacientes de todas las edades.',
    queAprenderas: [
      'Anatomía, fisiología y patologías comunes',
      'Técnicas de cuidado y atención al paciente',
      'Farmacología y administración de medicamentos',
      'Urgencias, emergencias y primeros auxilios',
    ],
    salidasProfesionales: [
      'Técnico/a en Cuidados Auxiliares de Enfermería',
      'Técnico/a en Farmacia y Parafarmacia',
      'Técnico/a en Emergencias Sanitarias',
      'Técnico/a en Documentación Sanitaria',
      'Técnico/a en Anatomía Patológica',
    ],
    perfilTipico:
      'Personas con vocación de ayudar, alta empatía, capacidad de mantener la calma bajo presión y gran responsabilidad.',
    ciclosDestacados: [
      'Cuidados Auxiliares de Enfermería — Grado Medio',
      'Farmacia y Parafarmacia — Grado Medio',
      'Emergencias Sanitarias — Grado Medio',
      'Documentación y Administración Sanitarias — Grado Superior',
    ],
    ventajas: [
      'Trabajo con propósito real y impacto humano directo',
      'Gran estabilidad laboral — siempre hay demanda sanitaria',
      'Posibilidad de trabajar en el sistema público o privado',
    ],
    nivelRecomendado: 'Grado Medio',
    queryParam: 'Sanidad',
  },
  {
    codigo: 'ADG',
    nombre: 'Administración y Gestión',
    emoji: '📊',
    colorFrom: '#1e3a5f',
    colorTo: '#6366f1',
    textColor: 'white',
    weights: { negocio: 10, precision: 9, comunicacion: 6, tecnologia: 4 },
    tagline: 'Organiza y gestiona el motor de las empresas',
    descripcion:
      'Lleva la contabilidad, la gestión de recursos humanos y la administración de cualquier tipo de empresa u organización.',
    queAprenderas: [
      'Contabilidad y gestión financiera',
      'Recursos humanos y nóminas',
      'Comunicación empresarial y atención al cliente',
      'Ofimática avanzada y software de gestión (ERP)',
    ],
    salidasProfesionales: [
      'Administrativo/a de empresas',
      'Técnico/a en recursos humanos',
      'Gestor/a contable y financiero/a',
      'Asistente de dirección',
      'Técnico/a en comercio exterior',
    ],
    perfilTipico:
      'Personas organizadas, metódicas, con buena comunicación escrita y capacidad para manejar documentación y datos con precisión.',
    ciclosDestacados: [
      'Gestión Administrativa — Grado Medio',
      'Administración y Finanzas — Grado Superior',
      'Asistencia a la Dirección — Grado Superior',
    ],
    ventajas: [
      'Posibilidad de trabajar en cualquier sector empresarial',
      'Alta employabilidad en empresas de todos los tamaños',
      'Base perfecta para emprender tu propio negocio',
    ],
    nivelRecomendado: 'Cualquier nivel',
    queryParam: 'Administración y Gestión',
  },
  {
    codigo: 'COM',
    nombre: 'Comercio y Marketing',
    emoji: '🛒',
    colorFrom: '#7c2d12',
    colorTo: '#f59e0b',
    textColor: 'white',
    weights: { negocio: 8, comunicacion: 9, creatividad: 6, servicio: 5 },
    tagline: 'Conecta productos y personas con estrategia',
    descripcion:
      'Gestiona tiendas, comercio electrónico, estrategias de marketing digital y atención al cliente en entornos comerciales.',
    queAprenderas: [
      'Marketing digital y redes sociales',
      'Gestión de compraventa y logística comercial',
      'Atención al cliente y técnicas de venta',
      'Comercio electrónico y plataformas digitales',
    ],
    salidasProfesionales: [
      'Técnico/a en marketing digital',
      'Gestor/a de comercio electrónico',
      'Responsable de tienda o punto de venta',
      'Agente comercial y representante',
      'Community manager',
    ],
    perfilTipico:
      'Personas extrovertidas, con don de gentes, que disfrutan vendiendo ideas, convenciendo y conectando con distintos tipos de personas.',
    ciclosDestacados: [
      'Actividades Comerciales — Grado Medio',
      'Comercio Internacional — Grado Superior',
      'Marketing y Publicidad — Grado Superior',
    ],
    ventajas: [
      'Combinación perfecta de creatividad y estrategia empresarial',
      'Gran salida profesional en el auge del comercio online',
      'Posibilidad de trabajar como freelance o emprender',
    ],
    nivelRecomendado: 'Grado Superior',
    queryParam: 'Comercio y Marketing',
  },
  {
    codigo: 'ELE',
    nombre: 'Electricidad y Electrónica',
    emoji: '⚡',
    colorFrom: '#1c1917',
    colorTo: '#eab308',
    textColor: 'white',
    weights: { tecnologia: 9, fisico: 7, precision: 9, construccion: 5 },
    tagline: 'Instala y mantiene los sistemas que nos dan energía',
    descripcion:
      'Instala, mantiene y repara sistemas eléctricos, de telecomunicaciones y electrónicos en edificios, industrias y hogares.',
    queAprenderas: [
      'Instalaciones eléctricas en baja tensión',
      'Domótica y automatización del hogar',
      'Electrónica analógica y digital',
      'Telecomunicaciones e infraestructuras de red',
    ],
    salidasProfesionales: [
      'Electricista instalador/a',
      'Técnico/a de telecomunicaciones',
      'Técnico/a de mantenimiento industrial',
      'Especialista en domótica y automatización',
      'Técnico/a de electrónica de consumo',
    ],
    perfilTipico:
      'Personas con habilidad manual, que disfrutan entendiendo cómo funcionan los aparatos y sistemas eléctricos y son meticulosas con la seguridad.',
    ciclosDestacados: [
      'Instalaciones Eléctricas y Automáticas — Grado Medio',
      'Sistemas Electrotécnicos y Automatizados — Grado Superior',
      'Instalaciones de Telecomunicaciones — Grado Medio',
    ],
    ventajas: [
      'Demanda laboral constante en construcción e industria',
      'Trabajo mixto: técnico en oficina y práctico en obra',
      'Sector clave para las energías renovables',
    ],
    nivelRecomendado: 'Grado Medio',
    queryParam: 'Electricidad y Electrónica',
  },
  {
    codigo: 'HOT',
    nombre: 'Hostelería y Turismo',
    emoji: '🍽️',
    colorFrom: '#7c2d12',
    colorTo: '#ef4444',
    textColor: 'white',
    weights: { servicio: 10, comunicacion: 7, creatividad: 6, personas: 5 },
    tagline: 'Crea experiencias que la gente recordará siempre',
    descripcion:
      'Trabaja en restaurantes, hoteles, agencias de viajes y eventos creando experiencias gastronómicas y turísticas únicas.',
    queAprenderas: [
      'Técnicas culinarias y repostería',
      'Gestión y operaciones hoteleras',
      'Protocolo, sala y atención al cliente',
      'Gestión de viajes y turismo sostenible',
    ],
    salidasProfesionales: [
      'Cocinero/a y jefe/a de cocina',
      'Técnico/a en restauración y sala',
      'Recepcionista y técnico/a hotelero/a',
      'Agente de viajes y gestor/a turístico',
      'Organizador/a de eventos',
    ],
    perfilTipico:
      'Personas sociables, con pasión por la gastronomía o los viajes, capacidad de trabajar bajo presión y orientación total al cliente.',
    ciclosDestacados: [
      'Cocina y Gastronomía — Grado Medio',
      'Servicios en Restauración — Grado Medio',
      'Dirección de Cocina — Grado Superior',
      'Agencias de Viajes y Gestión de Eventos — Grado Superior',
    ],
    ventajas: [
      'Trabajo dinámico, nunca hay dos días iguales',
      'Alta empleabilidad en toda España y el extranjero',
      'Posibilidad de viajar y trabajar internacionalmente',
    ],
    nivelRecomendado: 'Cualquier nivel',
    queryParam: 'Hostelería y Turismo',
  },
  {
    codigo: 'IMP',
    nombre: 'Imagen Personal',
    emoji: '💇',
    colorFrom: '#831843',
    colorTo: '#ec4899',
    textColor: 'white',
    weights: { arte: 9, personas: 7, servicio: 8, creatividad: 8 },
    tagline: 'Transforma y embellece a las personas',
    descripcion:
      'Trabaja en peluquerías, centros de estética, spas y salones de imagen asesorando y transformando el aspecto de las personas.',
    queAprenderas: [
      'Técnicas de peluquería y colorimetría',
      'Tratamientos faciales y corporales',
      'Asesoría de imagen y estilo personal',
      'Maquillaje artístico y caracterización',
    ],
    salidasProfesionales: [
      'Peluquero/a y estilista',
      'Esteticista y técnico/a en tratamientos',
      'Asesor/a de imagen personal',
      'Maquillador/a profesional',
      'Gestor/a de salón de belleza',
    ],
    perfilTipico:
      'Personas con sensibilidad estética, don de gentes, habilidad manual y pasión por hacer que otros se sientan bien consigo mismos.',
    ciclosDestacados: [
      'Peluquería y Cosmética Capilar — Grado Medio',
      'Estética y Belleza — Grado Medio',
      'Estética Integral y Bienestar — Grado Superior',
      'Caracterización y Maquillaje Profesional — Grado Superior',
    ],
    ventajas: [
      'Alta posibilidad de trabajar por cuenta propia desde el primer año',
      'Trabajo creativo con resultados visibles e inmediatos',
      'Sector en constante crecimiento por la demanda de bienestar',
    ],
    nivelRecomendado: 'Cualquier nivel',
    queryParam: 'Imagen Personal',
  },
  {
    codigo: 'SCS',
    nombre: 'Servicios Socioculturales',
    emoji: '🤝',
    colorFrom: '#1e3a5f',
    colorTo: '#06b6d4',
    textColor: 'white',
    weights: { personas: 10, comunicacion: 8, servicio: 7, creatividad: 4 },
    tagline: 'Apoya a quienes más lo necesitan',
    descripcion:
      'Trabaja con niños, mayores, personas con diversidad funcional o en riesgo de exclusión, en centros sociales, colegios y residencias.',
    queAprenderas: [
      'Atención socioeducativa a la infancia',
      'Intervención social con personas mayores',
      'Técnicas de mediación y dinamización',
      'Apoyo a personas con discapacidad',
    ],
    salidasProfesionales: [
      'Técnico/a de integración social',
      'Educador/a infantil',
      'Animador/a sociocultural',
      'Técnico/a de atención a mayores',
      'Mediador/a intercultural',
    ],
    perfilTipico:
      'Personas con gran empatía, paciencia, vocación de servicio y capacidad para adaptarse a perfiles y situaciones muy distintas.',
    ciclosDestacados: [
      'Atención a Personas en Situación de Dependencia — Grado Medio',
      'Educación Infantil — Grado Superior',
      'Integración Social — Grado Superior',
      'Animación Sociocultural y Turística — Grado Superior',
    ],
    ventajas: [
      'Trabajo con un propósito claro y muy humano',
      'Gran demanda por el envejecimiento de la población',
      'Acceso a empleos en el sector público y privado',
    ],
    nivelRecomendado: 'Grado Superior',
    queryParam: 'Servicios Socioculturales y a la Comunidad',
  },
  {
    codigo: 'AFD',
    nombre: 'Actividades Físicas y Deportivas',
    emoji: '🏃',
    colorFrom: '#14532d',
    colorTo: '#22c55e',
    textColor: 'white',
    weights: { fisico: 10, personas: 7, ciencia: 5, servicio: 5 },
    tagline: 'Inspira a otros a moverse y superarse',
    descripcion:
      'Entrena, forma y gestiona actividades deportivas y de ocio activo para personas de todas las edades y condiciones físicas.',
    queAprenderas: [
      'Fundamentos del entrenamiento deportivo',
      'Animación y recreación deportiva',
      'Primeros auxilios y prevención de lesiones',
      'Gestión de instalaciones deportivas',
    ],
    salidasProfesionales: [
      'Entrenador/a personal y deportivo',
      'Monitor/a de actividades físicas',
      'Técnico/a de deporte escolar',
      'Gestor/a de instalaciones deportivas',
      'Socorrista y vigilante de playas/piscinas',
    ],
    perfilTipico:
      'Personas activas, apasionadas del deporte y la salud, con capacidad de liderazgo y motivación para inspirar a otros.',
    ciclosDestacados: [
      'Conducción de Actividades Físico-Deportivas — Grado Medio',
      'Animación de Actividades Físicas y Deportivas — Grado Superior',
    ],
    ventajas: [
      'Trabajo al aire libre y en entornos dinámicos',
      'Combinación perfecta de salud, deporte y educación',
      'Posibilidad de especializarte en múltiples disciplinas',
    ],
    nivelRecomendado: 'Cualquier nivel',
    queryParam: 'Actividades físicas y deportivas',
  },
  {
    codigo: 'EOC',
    nombre: 'Edificación y Obra Civil',
    emoji: '🏗️',
    colorFrom: '#292524',
    colorTo: '#78716c',
    textColor: 'white',
    weights: { construccion: 10, fisico: 8, precision: 8, negocio: 3 },
    tagline: 'Construye las infraestructuras del mañana',
    descripcion:
      'Trabaja en proyectos de construcción, reformas, obras civiles y gestión de obras desde el primer ladrillo hasta la entrega final.',
    queAprenderas: [
      'Técnicas de construcción y materiales',
      'Topografía y replanteo de obras',
      'Gestión de proyectos de edificación',
      'Prevención de riesgos laborales en obra',
    ],
    salidasProfesionales: [
      'Técnico/a de obra y construcción',
      'Delineante y técnico/a de proyectos',
      'Inspector/a de calidad en obra',
      'Jefe/a de obra y encargado/a',
      'Técnico/a de reformas y rehabilitación',
    ],
    perfilTipico:
      'Personas con habilidad espacial, que disfrutan viendo cómo sus proyectos toman forma física, meticulosas con la planificación y seguridad.',
    ciclosDestacados: [
      'Obras de Interior, Decoración y Rehabilitación — Grado Medio',
      'Proyectos de Edificación — Grado Superior',
      'Proyectos de Obra Civil — Grado Superior',
    ],
    ventajas: [
      'Sector que siempre tiene demanda laboral constante',
      'Trabajo con impacto visual real y duradero en el territorio',
      'Acceso a grandes empresas constructoras e ingenierías',
    ],
    nivelRecomendado: 'Grado Superior',
    queryParam: 'Edificación y obra civil',
  },
  {
    codigo: 'INM',
    nombre: 'Instalación y Mantenimiento',
    emoji: '🔧',
    colorFrom: '#1e3a5f',
    colorTo: '#64748b',
    textColor: 'white',
    weights: { fisico: 8, construccion: 9, tecnologia: 6, precision: 7 },
    tagline: 'Mantén en marcha los sistemas que todos usamos',
    descripcion:
      'Instala y mantiene sistemas de climatización, frío industrial, calefacción, fontanería y maquinaria en edificios e industrias.',
    queAprenderas: [
      'Instalaciones de climatización y calefacción',
      'Frío industrial y refrigeración',
      'Fontanería y redes de distribución de agua',
      'Mantenimiento de maquinaria industrial',
    ],
    salidasProfesionales: [
      'Técnico/a en climatización y frío',
      'Instalador/a y mantenedor/a de sistemas',
      'Técnico/a de mantenimiento industrial',
      'Especialista en eficiencia energética',
      'Técnico/a de instalaciones en edificios',
    ],
    perfilTipico:
      'Personas con habilidad técnica y manual, que disfrutan resolviendo averías, son meticulosas y no les asusta el trabajo en distintos entornos.',
    ciclosDestacados: [
      'Instalaciones de Producción de Calor — Grado Medio',
      'Instalaciones Frigoríficas y de Climatización — Grado Medio',
      'Mantenimiento de Instalaciones Térmicas y de Fluidos — Grado Superior',
    ],
    ventajas: [
      'Alta empleabilidad por la demanda en construcción y reforma',
      'Trabajo variado: nunca hay dos instalaciones iguales',
      'Sector clave en la transición energética y sostenibilidad',
    ],
    nivelRecomendado: 'Grado Medio',
    queryParam: 'Instalación y mantenimiento',
  },
  {
    codigo: 'AGA',
    nombre: 'Agricultura y Alimentación',
    emoji: '🌾',
    colorFrom: '#365314',
    colorTo: '#84cc16',
    textColor: 'white',
    weights: { naturaleza: 10, fisico: 7, ciencia: 5, precision: 5 },
    tagline: 'Cuida la tierra y lleva alimentos al mundo',
    descripcion:
      'Trabaja en el campo, la ganadería, industrias agroalimentarias y la gestión sostenible de los recursos naturales de Castilla y León.',
    queAprenderas: [
      'Producción agrícola y vegetal',
      'Ganadería y sanidad animal',
      'Industria alimentaria y conservación de alimentos',
      'Gestión sostenible del medio rural',
    ],
    salidasProfesionales: [
      'Técnico/a en producción agropecuaria',
      'Técnico/a en industria alimentaria',
      'Gestor/a de explotaciones agrarias',
      'Técnico/a en jardinería y paisajismo',
      'Técnico/a forestal y de medioambiente',
    ],
    perfilTipico:
      'Personas con amor por la naturaleza, el trabajo al aire libre, los animales y la producción sostenible de alimentos.',
    ciclosDestacados: [
      'Producción Agropecuaria — Grado Medio',
      'Gestión Forestal y del Medio Natural — Grado Medio',
      'Industrias Alimentarias — Grado Superior',
      'Gestión Forestal — Grado Superior',
    ],
    ventajas: [
      'Sector estratégico en Castilla y León, líder agroalimentario de España',
      'Trabajo al aire libre con impacto medioambiental directo',
      'Creciente demanda de técnicos en agricultura sostenible',
    ],
    nivelRecomendado: 'Cualquier nivel',
    queryParam: 'Agricultura, ganadería y pesca y alimentación',
  },
  {
    codigo: 'QUI',
    nombre: 'Química',
    emoji: '🧪',
    colorFrom: '#1e3a5f',
    colorTo: '#8b5cf6',
    textColor: 'white',
    weights: { ciencia: 10, precision: 9, naturaleza: 5, tecnologia: 3 },
    tagline: 'Transforma la materia para mejorar el mundo',
    descripcion:
      'Trabaja en laboratorios, plantas industriales y empresas farmacéuticas controlando y analizando procesos químicos y bioquímicos.',
    queAprenderas: [
      'Técnicas analíticas de laboratorio',
      'Procesos industriales químicos',
      'Control de calidad y seguridad en planta',
      'Química medioambiental y sostenibilidad',
    ],
    salidasProfesionales: [
      'Técnico/a de laboratorio analítico',
      'Operador/a de planta química',
      'Técnico/a de control de calidad',
      'Especialista en medio ambiente',
      'Técnico/a en plásticos y caucho',
    ],
    perfilTipico:
      'Personas con pasión por la ciencia, la exactitud y el rigor experimental, que disfrutan observando cómo reaccionan los materiales.',
    ciclosDestacados: [
      'Operaciones de Laboratorio — Grado Medio',
      'Laboratorio de Análisis y de Control de Calidad — Grado Superior',
      'Química Industrial — Grado Superior',
    ],
    ventajas: [
      'Trabajo en sectores de alto valor: farmacia, alimentación, energía',
      'Base científica que abre puertas a muchos sectores industriales',
      'Alta precisión y rigor: ideal para perfiles muy meticulosos',
    ],
    nivelRecomendado: 'Grado Superior',
    queryParam: 'Química',
  },
  {
    codigo: 'ARP',
    nombre: 'Artes Plásticas y Diseño',
    emoji: '🎨',
    colorFrom: '#500724',
    colorTo: '#a855f7',
    textColor: 'white',
    weights: { arte: 10, creatividad: 10, fisico: 5, comunicacion: 4 },
    tagline: 'Da forma y color a las ideas más originales',
    descripcion:
      'Diseña objetos, espacios, ilustraciones y elementos visuales combinando la técnica artística con la creatividad más libre.',
    queAprenderas: [
      'Dibujo artístico y técnico',
      'Diseño gráfico y digital',
      'Fotografía y edición de imagen',
      'Diseño de interiores y escenografía',
    ],
    salidasProfesionales: [
      'Diseñador/a gráfico/a o de producto',
      'Ilustrador/a y artista visual',
      'Fotógrafo/a profesional',
      'Técnico/a en artes aplicadas',
      'Diseñador/a de espacios e interiores',
    ],
    perfilTipico:
      'Personas con sensibilidad artística muy marcada, que sienten la necesidad de crear y expresarse visualmente y tienen buen ojo estético.',
    ciclosDestacados: [
      'Artes Aplicadas al Muro — Grado Superior',
      'Fotografía Artística — Grado Superior',
      'Diseño de Interiores — Grado Superior',
    ],
    ventajas: [
      'Gran libertad creativa y posibilidades de expresión propias',
      'Alta demanda en publicidad, diseño digital y arquitectura',
      'Posibilidad de trabajar como freelance desde el primer día',
    ],
    nivelRecomendado: 'Grado Superior',
    queryParam: 'Artes plásticas',
  },
];
