<?php
namespace App\Rules;

use Closure;
use Illuminate\Contracts\Validation\ValidationRule;

/**
 * NOT DISPOSABLE EMAIL RULE
 *
 * Rechaza emails de dominios temporales/desechables conocidos.
 * Estos dominios se usan frecuentemente para spam y cuentas fake.
 */
class NotDisposableEmail implements ValidationRule
{
    // Lista de dominios de email desechables más comunes
    private array $disposableDomains = [
        // Temporales populares
        'tempmail.com', 'temp-mail.org', 'tempail.com', 'tempr.email',
        'tempinbox.com', 'temp-mail.io', 'tempmailo.com',
        '10minutemail.com', '10minutemail.net', '10minutemail.org',
        '10minmail.com', '10minemail.com',
        'guerrillamail.com', 'guerrillamail.org', 'guerrillamail.net',
        'guerrillamail.biz', 'guerrillamail.de', 'grr.la', 'guerrillamailblock.com',
        'mailinator.com', 'mailinator.net', 'mailinator.org', 'mailinator2.com',
        'mailinater.com', 'mailinator.us',
        'throwaway.email', 'throwawaymail.com',
        'fakeinbox.com', 'fakemailgenerator.com',
        'yopmail.com', 'yopmail.fr', 'yopmail.net',
        'dispostable.com', 'disposableemailaddresses.com',
        'trashmail.com', 'trashmail.net', 'trashmail.org', 'trashemail.de',
        'mailnesia.com', 'mailnull.com',
        'getnada.com', 'nada.email',
        'sharklasers.com', 'spam4.me', 'spamgourmet.com',
        'mytemp.email', 'mohmal.com', 'emailondeck.com',
        'crazymailing.com', 'maildrop.cc',
        'mintemail.com', 'mt2009.com', 'mt2014.com',
        'dropmail.me', 'getairmail.com',
        'mailcatch.com', 'mailscrap.com', 'mailsac.com',
        'spambox.us', 'spamfree24.org', 'spamherelots.com',
        'spamobox.com', 'temporaryemail.net', 'tmpmail.org', 'tmpmail.net',
        'wegwerfmail.de', 'wegwerfmail.net', 'wegwerfmail.org',
        '33mail.com', 'amilegit.com', 'anonymbox.com',
        'antispam.de', 'binkmail.com', 'bobmail.info',
        'bofthew.com', 'boun.cr', 'bouncr.com',
        'bugmenot.com', 'bumpymail.com', 'casualdx.com',
        'cheatmail.de', 'consumerriot.com', 'cool.fr.nf',
        'correo.blogos.net', 'cosmorph.com', 'courriel.fr.nf',
        'curryworld.de', 'cust.in', 'dacoolest.com',
        'dandikmail.com', 'deadaddress.com', 'despam.it',
        'devnullmail.com', 'dfgh.net', 'digitalsanctuary.com',
        'discardmail.com', 'discardmail.de', 'disposable.com',
        'disposableaddress.com', 'disposableemailaddresses.com',
        'disposableinbox.com', 'dispose.it', 'disposeamail.com',
        'dispomail.eu', 'dm.w3internet.co.uk', 'dodgeit.com',
        'dodgit.com', 'dodgit.org', 'dontreg.com', 'dontsendmespam.de',
        'dump-email.info', 'dumpandjunk.com', 'dumpmail.de',
        'dumpyemail.com', 'e4ward.com', 'easytrashmail.com',
        'emailgo.de', 'emailias.com', 'emailigo.de',
        'emailinfive.com', 'emaillime.com', 'emailmiser.com',
        'emailsensei.com', 'emailtemporanea.com', 'emailtemporanea.net',
        'emailtemporar.ro', 'emailtemporario.com.br', 'emailthe.net',
        'emailtmp.com', 'emailto.de', 'emailwarden.com',
        'emailx.at.hm', 'emailxfer.com', 'emz.net',
        'enterto.com', 'ephemail.net', 'ero-tube.org',
        'etranquil.com', 'etranquil.net', 'etranquil.org',
        'evopo.com', 'explodemail.com', 'express.net.ua',
        'eyepaste.com', 'fakeinbox.com', 'fakeinformation.com',
        'fansworldwide.de', 'fastacura.com', 'fastchevy.com',
        'fastchrysler.com', 'fastkawasaki.com', 'fastmazda.com',
        'fastmitsubishi.com', 'fastnissan.com', 'fastsubaru.com',
        'fastsuzuki.com', 'fasttoyota.com', 'fastyamaha.com',
        'filzmail.com', 'fixmail.tk', 'fizmail.com',
        'flyspam.com', 'fr33mail.info', 'frapmail.com',
        'friendlymail.co.uk', 'front14.org', 'fuckingduh.com',
        'fudgerub.com', 'garliclife.com', 'gehensiull.com',
        'get1mail.com', 'get2mail.fr', 'getonemail.com',
        'getonemail.net', 'ghosttexter.de', 'girlsundertheinfluence.com',
        'gishpuppy.com', 'gmial.com', 'goemailgo.com',
        'gotmail.com', 'gotmail.net', 'gotmail.org',
        'gotti.otherinbox.com', 'great-host.in', 'greensloth.com',
        'gsrv.co.uk', 'haltospam.com', 'hatespam.org',
        'herp.in', 'hidemail.de', 'hidzz.com',
        'hmamail.com', 'hopemail.biz', 'hotpop.com',
        'hulapla.de', 'ieatspam.eu', 'ieatspam.info',
        'ihateyoualot.info', 'iheartspam.org', 'imails.info',
        'imgof.com', 'imgv.de', 'imstations.com',
        'inbax.tk', 'inbox.si', 'inboxalias.com',
        'inboxclean.com', 'inboxclean.org', 'incognitomail.com',
        'incognitomail.net', 'incognitomail.org', 'infocom.zp.ua',
        'insorg-mail.info', 'instant-mail.de', 'instantemailaddress.com',
        'iozak.com', 'ipoo.org', 'irish2me.com',
        'iwi.net', 'jetable.com', 'jetable.fr.nf',
        'jetable.net', 'jetable.org', 'jnxjn.com',
        'jobbikszansen.com', 'kasmail.com', 'keepmymail.com',
        'killmail.com', 'killmail.net', 'kimsdisk.com',
        'kingsq.ga', 'klassmaster.com', 'klassmaster.net',
        'klzlv.com', 'kulturbetrieb.info', 'kurzepost.de',
        'lackmail.net', 'lags.us', 'lawlita.com',
        'letthemeatspam.com', 'lhsdv.com', 'lifebyfood.com',
        'link2mail.net', 'litedrop.com', 'loadby.us',
        'login-email.ml', 'lol.ovpn.to', 'lookugly.com',
        'lopl.co.cc', 'lortemail.dk', 'lovemeleaveme.com',
        'lr78.com', 'lroid.com', 'lukop.dk',
        'maboard.com', 'mail-hierarchie.net', 'mail-temporaire.fr',
        'mail.by', 'mail.mezimages.net', 'mail.zp.ua',
        'mail114.net', 'mail2rss.org', 'mail333.com',
        'mail4trash.com', 'mailbidon.com', 'mailblocks.com',
        'mailbucket.org', 'mailcat.biz', 'mailcz.info',
        'mailde.de', 'mailde.info', 'maildrop.cc',
        'maildrop.cf', 'maildrop.ga', 'maildrop.gq',
        'maildrop.ml', 'maildu.de', 'maileater.com',
        'mailed.in', 'mailexpire.com', 'mailfa.tk',
        'mailforspam.com', 'mailfree.ga', 'mailfree.gq',
        'mailfree.ml', 'mailfreeonline.com', 'mailguard.me',
        'mailhazard.com', 'mailhazard.us', 'mailhz.me',
        'mailimate.com', 'mailin8r.com', 'mailinater.com',
        'mailinator.gq', 'mailinator.info', 'mailinator.co',
        'mailinblack.com', 'mailincubator.com', 'mailismagic.com',
        'mailjunk.cf', 'mailjunk.ga', 'mailjunk.gq',
        'mailjunk.ml', 'mailjunk.tk', 'mailmate.com',
        'mailme.gq', 'mailme.ir', 'mailme.lv',
        'mailme24.com', 'mailmetrash.com', 'mailmoat.com',
        'mailnator.com', 'mailnesia.com', 'mailnull.com',
        'mailorg.org', 'mailpick.biz', 'mailproxsy.com',
        'mailquack.com', 'mailrock.biz', 'mailsac.com',
        'mailscrap.com', 'mailseal.de', 'mailshell.com',
        'mailsiphon.com', 'mailslapping.com', 'mailslite.com',
        'mailspam.xyz', 'mailspeed.ru', 'mailtechx.com',
        'mailtome.de', 'mailtothis.com', 'mailtrash.net',
        'mailtv.net', 'mailtv.tv', 'mailzilla.com',
        'mailzilla.org', 'mailzilla.orgmbx.cc', 'makemetheking.com',
        'manifestgenerator.com', 'manybrain.com', 'mbx.cc',
        'mega.zik.dj', 'meinspamschutz.de', 'meltmail.com',
        'messagebeamer.de', 'mezimages.net', 'mierdamail.com',
        'migmail.pl', 'migumail.com', 'mintemail.com',
        'mjukgansen.nu', 'moakt.com', 'moakt.ws',
        'mobileninja.co.uk', 'moburl.com', 'moncourrier.fr.nf',
        'monemail.fr.nf', 'monmail.fr.nf', 'monumentmail.com',
        'ms9.mailslite.com', 'msb.minsmail.com', 'msg.mailslite.com',
        'mspeciosa.com', 'msa.minsmail.com', 'mswork.ru',
        'mt2009.com', 'mt2014.com', 'mymail-in.net',
        'mynetstore.de', 'mypacks.net', 'mypartyclip.de',
        'myphantomemail.com', 'mysamp.de', 'myspaceinc.com',
        'myspaceinc.net', 'myspacepimpedup.com', 'mytempemail.com',
        'mytempmail.com', 'mytrashmail.com', 'nabuma.com',
        'neomailbox.com', 'nepwk.com', 'nervmich.net',
        'nervtmansen.com', 'netmails.com', 'netmails.net',
        'netzidiot.de', 'neverbox.com', 'nice-4u.com',
        'nincsmail.hu', 'nmail.cf', 'nobulk.com',
        'noclickemail.com', 'nogmailspam.info', 'nomail.pw',
        'nomail.xl.cx', 'nomail2me.com', 'nomorespamemails.com',
        'nospam.ze.tc', 'nospam4.us', 'nospamfor.us',
        'nospammail.net', 'nospamthanks.info', 'notmailinator.com',
        'nowhere.org', 'nowmymail.com', 'nurfuerspam.de',
        'nus.edu.sg', 'nwldx.com', 'objectmail.com',
        'obobbo.com', 'odnorazovoe.ru', 'ohaaa.de',
        'omail.pro', 'oneoffemail.com', 'oneoffmail.com',
        'onewaymail.com', 'onlatedotcom.info', 'online.ms',
        'oopi.org', 'opayq.com', 'ordinaryamerican.net',
        'otherinbox.com', 'ourklips.com', 'outlawspam.com',
        'ovpn.to', 'owlpic.com', 'pancakemail.com',
        'pimpedupmyspace.com', 'pjjkp.com', 'plexolan.de',
        'poczta.onet.pl', 'politikerclub.de', 'poofy.org',
        'pookmail.com', 'powered.name', 'privacy.net',
        'privatdemail.net', 'privy-mail.com', 'privymail.de',
        'proxymail.eu', 'prtnx.com', 'punkass.com',
        'putthisinyourspamdatabase.com', 'pwrby.com', 'qq.com',
        'quickinbox.com', 'quickmail.nl', 'radicalz.com',
        'rcpt.at', 're-gister.com', 'readmymail.com',
        'realtyalerts.ca', 'receiveee.chickenkiller.com', 'receiveee.com',
        'recursor.net', 'recyclemail.dk', 'regbypass.com',
        'regbypass.comsafe-mail.net', 'rejectmail.com', 'remail.cf',
        'remail.ga', 'rhyta.com', 'rklips.com',
        'rmqkr.net', 'royal.net', 'rppkn.com',
        'rtrtr.com', 's0ny.net', 'safe-mail.net',
        'safersignup.de', 'safetymail.info', 'safetypost.de',
        'sandelf.de', 'saynotospams.com', 'schafmail.de',
        'schrott-email.de', 'secretemail.de', 'secure-mail.biz',
        'selfdestructingmail.com', 'senseless-entertainment.com', 'server.ms.selfip.net',
        'sharklasers.com', 'shieldemail.com', 'shiftmail.com',
        'shitmail.me', 'shortmail.net', 'sibmail.com',
        'sinnlos-mail.de', 'siteposter.net', 'skeefmail.com',
        'slaskpost.se', 'slave-auctions.net', 'slopsbox.com',
        'slowfoodfoothills.com', 'smashmail.de', 'smellfear.com',
        'snakemail.com', 'sneakemail.com', 'sneakmail.de',
        'snkmail.com', 'sofimail.com', 'sofort-mail.de',
        'softpls.asia', 'sogetthis.com', 'sohu.com',
        'soisz.com', 'solvemail.info', 'soodonims.com',
        'spam.la', 'spam.su', 'spam4.me',
        'spamail.de', 'spamarrest.com', 'spamavert.com',
        'spambob.com', 'spambob.net', 'spambob.org',
        'spambog.com', 'spambog.de', 'spambog.net',
        'spambog.ru', 'spambox.info', 'spambox.irishspringrealty.com',
        'spambox.us', 'spamcannon.com', 'spamcannon.net',
        'spamcero.com', 'spamcon.org', 'spamcorptastic.com',
        'spamcowboy.com', 'spamcowboy.net', 'spamcowboy.org',
        'spamday.com', 'spamex.com', 'spamfree.eu',
        'spamfree24.com', 'spamfree24.de', 'spamfree24.eu',
        'spamfree24.info', 'spamfree24.net', 'spamfree24.org',
        'spamgoes.in', 'spamgourmet.com', 'spamgourmet.net',
        'spamgourmet.org', 'spamherelots.com', 'spamhereplease.com',
        'spamhole.com', 'spamify.com', 'spaminator.de',
        'spamkill.info', 'spaml.com', 'spaml.de',
        'spamlot.net', 'spammotel.com', 'spamobox.com',
        'spamoff.de', 'spamsalad.in', 'spamslicer.com',
        'spamspot.com', 'spamstack.net', 'spamthis.co.uk',
        'spamtroll.net', 'speed.1s.fr', 'spikio.com',
        'spoofmail.de', 'squizzy.de', 'ssoia.com',
        'startkeys.com', 'stinkefinger.net', 'stop-my-spam.cf',
        'stop-my-spam.com', 'stop-my-spam.ga', 'stop-my-spam.ml',
        'stop-my-spam.tk', 'streetwisemail.com', 'stuffmail.de',
        'supergreatmail.com', 'supermailer.jp', 'superrito.com',
        'superstachel.de', 'suremail.info', 'svk.jp',
        'sweetxxx.de', 'tafmail.com', 'tagyourself.com',
        'talkinator.com', 'tapchicuoihoi.com', 'techemail.com',
        'techgroup.me', 'teewars.org', 'teleosaurs.xyz',
        'teleworm.com', 'teleworm.us', 'temp.bartdevos.be',
        'temp.headstrong.de', 'tempail.com', 'tempalias.com',
        'tempe-mail.com', 'tempemail.biz', 'tempemail.co.za',
        'tempemail.com', 'tempemail.net', 'tempemail.org',
        'tempinbox.co.uk', 'tempinbox.com', 'tempmail.co',
        'tempmail.it', 'tempmail.net', 'tempmail.us',
        'tempmail2.com', 'tempmaildemo.com', 'tempmailer.com',
        'tempmailer.de', 'tempmailid.com', 'tempomail.fr',
        'temporarily.de', 'temporarioemail.com.br', 'temporaryemail.net',
        'temporaryemail.us', 'temporaryforwarding.com', 'temporaryinbox.com',
        'temporarymailaddress.com', 'tempthe.net', 'thanksobama.co',
        'thankyou2010.com', 'thc.st', 'thelimestones.com',
        'thisisnotmyrealemail.com', 'thismail.net', 'thismail.ru',
        'throam.com', 'throwawayemailaddress.com', 'throwawaymail.com',
        'tilien.com', 'tmail.ws', 'tmailinator.com',
        'tmpeml.info', 'toiea.com', 'toomail.biz',
        'topranklist.de', 'tradermail.info', 'trash-amil.com',
        'trash-mail.at', 'trash-mail.com', 'trash-mail.de',
        'trash-mail.ga', 'trash-mail.gq', 'trash-mail.ml',
        'trash-mail.tk', 'trash2009.com', 'trash2010.com',
        'trash2011.com', 'trashbox.eu', 'trashdevil.com',
        'trashdevil.de', 'trashemail.de', 'trashmail.at',
        'trashmail.com', 'trashmail.de', 'trashmail.me',
        'trashmail.net', 'trashmail.org', 'trashmail.ws',
        'trashmailer.com', 'trashymail.com', 'trashymail.net',
        'trbvm.com', 'trbvn.com', 'trialmail.de',
        'trickmail.net', 'trillianpro.com', 'tryalert.com',
        'turual.com', 'twinmail.de', 'tyldd.com',
        'ubismail.net', 'uggsrock.com', 'umail.net',
        'upliftnow.com', 'uplipht.com', 'uroid.com',
        'us.af', 'valemail.net', 'venompen.com',
        'veryrealemail.com', 'viditag.com', 'viewcastmedia.com',
        'viewcastmedia.net', 'viewcastmedia.org', 'viralplays.com',
        'vkcode.ru', 'vpn.st', 'vsimcard.com',
        'vubby.com', 'vztc.com', 'walala.org',
        'walkmail.net', 'wealthymoney.net', 'webemail.me',
        'webm4il.info', 'webuser.in', 'wee.my',
        'weg-werf-email.de', 'wegwerf-email-addressen.de', 'wegwerf-email.at',
        'wegwerf-emails.de', 'wegwerfadresse.de', 'wegwerfemail.com',
        'wegwerfemail.de', 'wegwerfmail.de', 'wegwerfmail.info',
        'wegwerfmail.net', 'wegwerfmail.org', 'wetrainbayarea.com',
        'wetrainbayarea.org', 'wh4f.org', 'whatiaas.com',
        'whatpaas.com', 'whopy.com', 'whtjddn.33mail.com',
        'whyspam.me', 'willhackforfood.biz', 'willselfdestruct.com',
        'winemaven.info', 'wmail.cf', 'wolfsmail.tk',
        'wollan.info', 'worldspace.link', 'wronghead.com',
        'wuzup.net', 'wuzupmail.net', 'wwwnew.eu',
        'x.ip6.li', 'xagloo.com', 'xemaps.com',
        'xents.com', 'xmaily.com', 'xoxy.net',
        'yapped.net', 'yep.it', 'yogamaven.com',
        'yopmail.com', 'yopmail.fr', 'yopmail.gq',
        'yopmail.net', 'you-spam.com', 'youmail.ga',
        'ypmail.webarnak.fr.eu.org', 'yuurok.com', 'yxzx.net',
        'z1p.biz', 'za.com', 'zehnminuten.de',
        'zehnminutenmail.de', 'zeta-telecom.com', 'zippymail.info',
        'zoaxe.com', 'zoemail.com', 'zoemail.net',
        'zoemail.org', 'zomg.info', 'zxcv.com',
        'zxcvbnm.com', 'zzz.com',
    ];

    public function validate(string $attribute, mixed $value, Closure $fail): void
    {
        if (!$value || !is_string($value)) {
            return;
        }

        $email = strtolower(trim($value));
        $domain = substr(strrchr($email, '@'), 1);

        if (!$domain) {
            return;
        }

        if (in_array($domain, $this->disposableDomains)) {
            $fail('No se permiten direcciones de email temporales o desechables.');
        }
    }
}
?>